name: CI - Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
    steps:
      - uses: actions/checkout@v4
      - name: Use Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps
      - name: Run tests (${{ matrix.browser }})
        run: |
          pytest -q --base-url="https://www.saucedemo.com/" --browser=${{ matrix.browser }} --maxfail=1 --dist=loadscope --junitxml=reports/junit-${{ matrix.browser }}.xml || true
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ matrix.browser }}
          path: reports/screenshots/**
      - name: Upload junit
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-${{ matrix.browser }}
          path: reports/junit-${{ matrix.browser }}.xml